// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCogRrJUXmPY96E4H0Yvx0UL5sMHvZf1qA',
    appId: '1:738939786577:web:6b7d0f6525fd3989fa2f70',
    messagingSenderId: '738939786577',
    projectId: 'social-media-application-7bd0d',
    authDomain: 'social-media-application-7bd0d.firebaseapp.com',
    storageBucket: 'social-media-application-7bd0d.appspot.com',
    measurementId: 'G-84TDZ4QR7L',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDP1cBhHrsvvujStuoIrtJKlggVtPjAouk',
    appId: '1:738939786577:android:1ea634565eb391dafa2f70',
    messagingSenderId: '738939786577',
    projectId: 'social-media-application-7bd0d',
    storageBucket: 'social-media-application-7bd0d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDN08s1_3JDiWld3SQRt82EGfrm2IyMRaA',
    appId: '1:738939786577:ios:551e1238e347161efa2f70',
    messagingSenderId: '738939786577',
    projectId: 'social-media-application-7bd0d',
    storageBucket: 'social-media-application-7bd0d.appspot.com',
    iosBundleId: 'com.example.socialMediaApplication',
  );
}
